### ISSUE TITLE
Dragging Color Selector to Bottom Crashes Application

### ISSUE THREAD

**Issue by jamsoft** [wieslawsoltes/ColorPicker#22] opened 2022-06-28 09:11 UTC
AvaloniaUI 0.10.15
ColorPicker 0.10.14

I have a color picker declared like this:

```
<colorPicker:ColorPicker x:Name="main"
                                 Grid.ColumnSpan="2"
                                 Margin="10" 
                                 Color="{Binding CurrentColor, Mode=TwoWay}">
    <colorPicker:ColorPicker.Styles>
        <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerValuesPresenter">
            <Setter Property="MinHeight" Value="200" />
            <Setter Property="MinWidth" Value="200" />
            <Setter Property="IsVisible" Value="True" />
        </Style>
        <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerPropertiesPresenter#PART_ColorPickerPropertiesPresenter">
            <Setter Property="(DockPanel.Dock)" Value="Right" />
            <Setter Property="IsVisible" Value="False" />
        </Style>
    </colorPicker:ColorPicker.Styles>
</colorPicker:ColorPicker>
```
Everything is working fine, the two way binding is updating correctly. `CurrentColor` is of Type `Avalonia.Media.Color`.

The issue manifests when the color selector is dragged to the extreme bottom edge. Which errors here:

```
private static bool ValidateValue(double value)
{
    if (value < 0.0 || value > 100.0)
    {
        throw new ArgumentException("Invalid Value value.");
    }
    return true;
}
```
With the following stack trace.
```
System.ArgumentException: Invalid Value value.
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.ValidateValue(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 54
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 98
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.set_Value(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 83
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.UpdatePropertyValues() in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 105
   at ThemeEditor.Controls.ColorPicker.ColorPickerProperties.<OnColorPickerChange>b__12_2(Double _) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerProperties.cs:line 55
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 67
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 761
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 355
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 284
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 107
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.set_Value3(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 56
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.UpdateValuesFromThumbs() in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 220
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.ColorCanvas_PointerMoved(Object sender, PointerEventArgs e) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 311
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, Lazy`1 intermediatePoints) in /_/src/Avalonia.Input/MouseDevice.cs:line 292
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 182
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 90
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 504
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 520
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
```
If I have some time later I'll pull the source into my project and see if I can identify the cause.

**Comment by wieslawsoltes** [comment] 2022-08-01 07:43
I think this might be duplicate of https://github.com/wieslawsoltes/ColorPicker/issues/21 and probably fixed by https://github.com/wieslawsoltes/ColorPicker/commit/cdb406e309d7f36f2b06a3f0dc14bf2036ca281a

**Comment by jamsoft** [comment] 2022-08-01 08:03
Yeah I was just thinking the same as I was reviewing your fix. It's almost certainly the same issue.

I had wondered if it was possibly picking up mouse values from outside it's `Bounds` hence the `NaN` but I think you're right.

**Comment by wieslawsoltes** [comment] 2022-08-01 08:05
> Yeah I was just thinking the same as I was reviewing your fix. It's almost certainly the same issue.
> 
> I had wondered if it was possibly picking up mouse values from outside it's `Bounds` hence the `NaN` but I think you're right.

Oh NaN that might be different issue

**Comment by wieslawsoltes** [comment] 2022-08-01 08:13
Added coercion for NaN values so exception can be avoided hopefully

**Comment by jamsoft** [comment] 2022-08-01 08:13
Sounds like a good idea

**Comment by wieslawsoltes** [comment] 2022-08-01 09:27
Release version 0.10.17 with a fix

**Closed** 2022-08-02 06:02 UTC
Labels: bug

**Comment by jamsoft** [comment] 2022-08-02 22:21
Yeah I tested this the other day, still seems to be crashing my app so I need to do a bit more digging on this one.

**Comment by jamsoft** [comment] 2022-08-06 07:27
Still seeing some odd issues with 0.10.17 unfortunately.

If I remove any `Binding` on `Color` and run the app, viewing the page with the `ColorPicker` on immediately bombs the app.

I decided to remove all of my logic and so just set the Color property to a fixed value with no binding:

```xaml
<colorPicker:ColorPicker x:Name="main"
                                 Grid.ColumnSpan="2"
                                 Margin="10" 
                                 Color="White">
    <colorPicker:ColorPicker.Styles>
        <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerValuesPresenter">
            <Setter Property="MinHeight" Value="200" />
            <Setter Property="MinWidth" Value="200" />
            <Setter Property="IsVisible" Value="True" />
        </Style>
        <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerPropertiesPresenter#PART_ColorPickerPropertiesPresenter">
            <Setter Property="(DockPanel.Dock)" Value="Right" />
            <Setter Property="IsVisible" Value="False" />
        </Style>
    </colorPicker:ColorPicker.Styles>
</colorPicker:ColorPicker>
```
Viewing the page works just fine. But dragging the color thumb to the bottom of the `ColorPickerValuesPresenter` viewable area is still bombing the app.

```
System.ArgumentException: Invalid Value value.
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.ValidateValue(Nullable`1 value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 86
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 98
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.set_Value(Nullable`1 value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 115
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.UpdatePropertyValues() in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 137
   at ThemeEditor.Controls.ColorPicker.ColorPickerProperties.<OnColorPickerChange>b__12_2(Nullable`1 _) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerProperties.cs:line 55
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 67
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 761
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 355
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 284
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 107
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.set_Value3(Nullable`1 value) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 55
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.UpdateValuesFromThumbs() in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 219
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.ColorCanvas_PointerMoved(Object sender, PointerEventArgs e) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 310
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 62
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args) in /_/src/Avalonia.Interactivity/Interactive.cs:line 68
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 167
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 101
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 122
   at Avalonia.Input.MouseDevice.MouseMove(IMouseDevice device, UInt64 timestamp, IInputRoot root, Point p, PointerPointProperties properties, KeyModifiers inputModifiers, Lazy`1 intermediatePoints) in /_/src/Avalonia.Input/MouseDevice.cs:line 292
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 182
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 90
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 35
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 508
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 520
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 30
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
```

**Comment by jamsoft** [comment] 2022-08-13 11:04
I've removed all my logic and tested again.

This control is still bombing my application.

```xaml
                    <colorPicker:ColorPicker x:Name="main"
                                                     Grid.ColumnSpan="2"
                                                     Margin="10" 
                                                     Color="White">
                        <colorPicker:ColorPicker.Styles>
                            <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerValuesPresenter">
                                <Setter Property="MinHeight" Value="200" />
                                <Setter Property="MinWidth" Value="200" />
                                <Setter Property="IsVisible" Value="True" />
                            </Style>
                            <Style Selector="colorPicker|ColorPicker /template/ colorPicker|ColorPickerPropertiesPresenter#PART_ColorPickerPropertiesPresenter">
                                <Setter Property="(DockPanel.Dock)" Value="Right" />
                                <Setter Property="IsVisible" Value="False" />
                            </Style>
                        </colorPicker:ColorPicker.Styles>
                    </colorPicker:ColorPicker>
```
```
System.ArgumentException: Invalid Value value.
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.ValidateValue(Nullable`1 value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 86
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 98
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.set_Value(Nullable`1 value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 115
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.UpdatePropertyValues() in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 137
```

**Comment by wieslawsoltes** [comment] 2022-08-13 13:14
I have refactored master branch and changed how validation and coercion of values works

**Comment by jamsoft** [comment] 2022-08-13 15:50
Ahhhh, OK. Will grab the latest and check it out. Thanks.

**Comment by jamsoft** [comment] 2022-08-14 06:40
Interestingly, the issue has now moved to the far right of the color swatch, hitting that extreme with the thumb bombs the demo.

The issue with the alpha slider is also still there. Dragging to the extreme bombs the demo.
