### ISSUE TITLE
When Color Property is DataBound, when Null Crashes Application

### ISSUE THREAD

**Issue by jamsoft** [wieslawsoltes/ColorPicker#21] opened 2022-06-24 10:34 UTC
When DataBinding the Color property to a property, when the property is null the ColorPicker crashes the application:

```
  at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.ValidateValue(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 54
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 98
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.set_Value(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 83
   at ThemeEditor.Controls.ColorPicker.Props.HsvProperties.UpdatePropertyValues() in /_/src/ThemeEditor.Controls.ColorPicker/Props/HsvProperties.cs:line 105
   at ThemeEditor.Controls.ColorPicker.ColorPickerProperties.<OnColorPickerChange>b__12_2(Double _) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerProperties.cs:line 55
   at System.Reactive.AnonymousObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousObserver.cs:line 67
   at System.Reactive.ObserverBase`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/ObserverBase.cs:line 34
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T value) in /_/src/Avalonia.Base/Reactive/LightweightObservableBase.cs:line 139
   at Avalonia.Reactive.AvaloniaPropertyObservable`1.PropertyChanged(Object sender, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Base/Reactive/AvaloniaPropertyObservable.cs:line 67
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 761
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 355
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 121
   at Avalonia.AvaloniaObject.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 367
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.set_Value3(Double value) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 56
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.UpdateValuesFromThumbs() in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 220
   at ThemeEditor.Controls.ColorPicker.ColorPickerValuesPresenter.OnColorChange() in /_/src/ThemeEditor.Controls.ColorPicker/ColorPickerValuesPresenter.cs:line 269
   at ThemeEditor.Controls.ColorPicker.ColorPicker.ArrangeOverride(Size finalSize) in /_/src/ThemeEditor.Controls.ColorPicker/ColorPicker.cs:line 80
```

Even specifying a binding Fallback value doesn't help.

Color="{Binding SelectedItem.Color, Converter={StaticResource ColorToStringConverter}, Mode=TwoWay, FallbackValue='#FFFFFFFF'}"

**Comment by wieslawsoltes** [comment] 2022-08-01 06:35
The issue is Color property is assumed to be never null, so type is Color. In order to make it work with null I need to add nullable annotations to that property and obviously null check where appropriate.

**Comment by wieslawsoltes** [comment] 2022-08-01 06:38
And still it can work most of time with null right now:
![image](https://user-images.githubusercontent.com/2297442/182087143-295f3990-5549-4578-af60-0c930d57374d.png)

**Comment by jamsoft** [comment] 2022-08-01 07:10
Gotcha. Makes sense.

**Comment by wieslawsoltes** [comment] 2022-08-01 07:11
Now I have to make byte and double nullables is the values are propagated everywhere :(

**Comment by wieslawsoltes** [comment] 2022-08-01 07:27
Anyway I am updating codebase to handle null, will be included in 0.10.17 release

**Comment by jamsoft** [comment] 2022-08-01 07:36
You know, I was thinking about looking into this this week as it's the final issue in my app before release. Your timing is amazing! :)

Thanks!

**Comment by wieslawsoltes** [comment] 2022-08-01 07:40
Potential fix: https://github.com/wieslawsoltes/ColorPicker/commit/cdb406e309d7f36f2b06a3f0dc14bf2036ca281a

**Comment by wieslawsoltes** [comment] 2022-08-01 09:27
Release version 0.10.17 with a fix

**Closed** 2022-08-02 06:02 UTC
Labels: bug
